Repository AY2021S1-CS2113T-F11-1/tp, pull requests merged in 2020-11, with the labels that each got.

#191 Fix workout session search bug
  src/main/java/commands/workout/workoutsession/WorkoutSessionSearch.java
Labels: bug, workout

#193 update search/list/ug/dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/commands/diet/dietmanager/DietSessionList.java
  src/main/java/commands/diet/dietmanager/DietSessionSearch.java
  src/main/java/commands/diet/dietsession/FoodItemList.java
  src/main/java/commands/diet/dietsession/FoodItemSearch.java
  src/main/java/diet/DateParser.java
  src/main/java/diet/dietmanager/DietManagerParser.java
Labels: bug, diet, documentation

#192 Update DG anchor in Storage session
  docs/DeveloperGuide.md
  src/main/java/profile/Constants.java
Labels: bug, documentation

#194 standardize print message
  src/main/java/commands/diet/dietmanager/DietSessionClear.java
  src/main/java/commands/diet/dietsession/FoodItemAdd.java
  src/main/java/commands/diet/dietsession/FoodItemClear.java
  src/main/java/diet/dietsession/Food.java
Labels: diet, priority.Low, severity.VeryLow

#195 Fixed issues in 2.1
  docs/UserGuide.md
  docs/pictures/khoa/AddProfile.puml
  docs/pictures/zesong/DeleteWS.png
  docs/pictures/zesong/DeleteWS.puml
  docs/pictures/zesong/NewWS.png
  docs/pictures/zesong/NewWS.puml
  src/main/java/commands/diet/dietmanager/DietSessionSearch.java
  src/main/java/commands/workout/workoutmanager/ClearWS.java
  src/main/java/diet/DateParser.java
  src/main/java/diet/dietmanager/DietManagerParser.java
  src/main/java/diet/dietsession/DietSession.java
  src/main/java/models/PastRecordList.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/ui/CommonUi.java
  src/main/java/ui/profile/ProfileUi.java
  src/main/java/ui/workout/workoutmanager/WorkoutManagerUi.java
  src/main/java/utils/DateParser.java
  src/main/java/workout/DateParser.java
  src/main/java/workout/workoutmanager/WorkoutManagerParser.java
  src/test/java/workout/DateParserTest.java
Labels: bug

#198 Update UG, DG; add common format for clear message in CommonUi
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/pictures/khoa/AddProfile.png
  docs/pictures/khoa/AddProfile.puml
  docs/pictures/khoa/DeleteProfile.png
  docs/pictures/khoa/DeleteProfile.puml
  docs/pictures/khoa/EditProfile.png
  docs/pictures/khoa/EditProfile.puml
  docs/pictures/khoa/ParseInput.png
  docs/pictures/khoa/ParseInput.puml
  docs/pictures/khoa/ViewProfile.png
  docs/pictures/khoa/ViewProfile.puml
  src/main/java/commands/diet/dietsession/FoodItemAdd.java
  src/main/java/commands/profile/ProfileAdd.java
  src/main/java/commands/profile/ProfileEdit.java
  src/main/java/profile/ProfileSession.java
  src/main/java/profile/Utils.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/ui/CommonUi.java
  src/main/java/ui/profile/ProfileUi.java
Labels: documentation, main

#201 Refactor methods and add more javadocs
  docs/UserGuide.md
  src/main/java/diet/dietmanager/DietManager.java
  src/main/java/diet/dietmanager/DietManagerParser.java
  src/main/java/diet/dietsession/DietSession.java
  src/main/java/exceptions/diet/InvalidSearchDateException.java
  src/main/java/logic/commands/Command.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionClear.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionCreate.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionDelete.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionEdit.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionHelp.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionList.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionSearch.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionWrong.java
  src/main/java/seedu/duke/Constant.java
  src/main/java/ui/diet/dietmanager/DietManagerUi.java
  src/test/java/diet/dietmanager/CommandLibTest.java
  src/test/java/diet/dietmanager/DietManagerParserTest.java
Labels: diet, priority.Low

#200 Add logo; Update Main Menu section in UG with screenshots
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/pictures/UG_screenshots/main-help-step-1.png
  docs/pictures/UG_screenshots/main-help-step-2.png
  docs/pictures/screenshots-labelling-template.pptx
  src/main/java/seedu/duke/Duke.java
  src/main/java/ui/CommonUi.java
Labels: documentation

#202 Refactor fooditem cmd
  src/main/java/diet/dietsession/DietSession.java
  src/main/java/logic/commands/Command.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionCreate.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionList.java
  src/main/java/logic/commands/diet/dietsession/FoodItemAdd.java
  src/main/java/logic/commands/diet/dietsession/FoodItemClear.java
  src/main/java/logic/commands/diet/dietsession/FoodItemDelete.java
  src/main/java/logic/commands/diet/dietsession/FoodItemHelp.java
  src/main/java/logic/commands/diet/dietsession/FoodItemList.java
  src/main/java/logic/commands/diet/dietsession/FoodItemSearch.java
  src/main/java/logic/commands/diet/dietsession/FoodItemWrong.java
  src/main/java/ui/diet/dietmanager/DietManagerUi.java
  src/main/java/ui/diet/dietsession/DietSessionUi.java
Labels: diet

#203 Refactored workout session commands
  src/main/java/logic/commands/Command.java
  src/main/java/logic/commands/workout/workoutsession/WorkoutSessionAdd.java
  src/main/java/logic/commands/workout/workoutsession/WorkoutSessionDelete.java
  src/main/java/logic/commands/workout/workoutsession/WorkoutSessionEnd.java
  src/main/java/logic/commands/workout/workoutsession/WorkoutSessionHelp.java
  src/main/java/logic/commands/workout/workoutsession/WorkoutSessionList.java
  src/main/java/logic/commands/workout/workoutsession/WorkoutSessionSearch.java
  src/main/java/logic/commands/workout/workoutsession/WorkoutSessionWrong.java
  src/main/java/ui/workout/workoutsession/WorkoutSessionUi.java
  src/main/java/workout/workoutsession/WorkoutSession.java
Labels: enhancement, workout

#204 Add test for workoutsession parser and add command
  src/main/java/workout/workoutsession/WorkoutSessionParser.java
  src/test/java/logic/commands/workout/workoutsession/WorkoutSessionAddTest.java
  src/test/java/workout/workoutsession/WorkoutSessionParserTest.java
Labels: workout

#205 Add more junit
  docs/DeveloperGuide.md
  docs/pictures/Shukai/FoodItemAdd.png
  docs/pictures/Shukai/FoodItemAdd.puml
  docs/pictures/Shukai/FoodItemList.puml
  docs/pictures/Zeon/CreateDietSession.png
  docs/pictures/Zeon/CreateDietSession.puml
  src/main/java/diet/dietmanager/DietManager.java
  src/main/java/diet/dietmanager/DietManagerParser.java
  src/main/java/diet/dietsession/DietSession.java
  src/main/java/diet/dietsession/DietSessionParser.java
  src/main/java/logic/commands/Command.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionList.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionSearch.java
  src/main/java/logic/commands/diet/dietsession/FoodItemAdd.java
  src/main/java/logic/commands/diet/dietsession/FoodItemClear.java
  src/main/java/logic/commands/diet/dietsession/FoodItemDelete.java
  src/main/java/logic/commands/diet/dietsession/FoodItemHelp.java
  src/main/java/logic/commands/diet/dietsession/FoodItemList.java
  src/main/java/logic/commands/diet/dietsession/FoodItemSearch.java
  src/main/java/logic/commands/diet/dietsession/FoodItemWrong.java
  src/main/java/logic/commands/profile/ProfileView.java
  src/main/java/models/Food.java
  src/test/java/diet/DietTest.java
  src/test/java/diet/dietmanager/DietManagerParserTest.java
  src/test/java/diet/dietmanager/DietManagerTest.java
  src/test/java/diet/dietsession/CommandLibTest.java
  src/test/java/diet/dietsession/DietSessionParserTest.java
  src/test/java/diet/dietsession/DietSessionTest.java
  src/test/java/diet/dietsession/DietSessionUiTest.java
Labels: diet

#207 Add test for Workout Session Add
  src/test/java/logic/commands/workout/workoutsession/WorkoutSessionAddTest.java
Labels: workout

#209 Add uml diagram
  DietSessionDelete.png
  docs/pictures/Shukai/FoodItemClear.png
  docs/pictures/Shukai/FoodItemClear.puml
  docs/pictures/Shukai/FoodItemDelete.png
  docs/pictures/Shukai/FoodItemDelete.puml
  docs/pictures/Shukai/FoodItemHelp.png
  docs/pictures/Shukai/FoodItemHelp.puml
  docs/pictures/Shukai/FoodItemList.png
  docs/pictures/Shukai/FoodItemList.puml
  docs/pictures/Shukai/FoodItemSearch.png
  docs/pictures/Shukai/FoodItemSearch.puml
  src/main/java/logic/commands/diet/dietsession/FoodItemAdd.java
  src/main/java/logic/commands/diet/dietsession/FoodItemClear.java
  src/main/java/logic/commands/diet/dietsession/FoodItemSearch.java
  src/main/java/ui/diet/dietsession/DietSessionUi.java
  src/test/java/logic/commands/diet/dietsession/FoodItemAddTest.java
  src/test/java/logic/commands/diet/dietsession/FoodItemClearTest.java
  src/test/java/logic/commands/diet/dietsession/FoodItemDeleteTest.java
Labels: diet, documentation

#210 Add Diet Storage Test and more javadocs
  src/main/java/diet/dietmanager/DietManager.java
  src/main/java/diet/dietsession/DietSession.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionClear.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionEdit.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionList.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionSearch.java
  src/main/java/storage/diet/DietStorage.java
  src/main/java/ui/diet/dietmanager/DietManagerUi.java
  src/test/java/diet/dietmanager/DietSessionStorageTest.java
  src/test/java/diet/dietmanager/saves/2020-05-04 breakfast.json
  src/test/java/diet/dietmanager/saves/2020-11-05 breakfast.json
Labels: diet

#211 update help in ug and fix help and add in diet session
  docs/UserGuide.md
  src/main/java/logic/commands/diet/dietsession/FoodItemAdd.java
  src/main/java/logic/commands/diet/dietsession/FoodItemHelp.java
  src/main/java/ui/diet/dietsession/DietSessionUi.java
Labels: bug, diet, documentation

#212 Add junit test for getDateTotalCalories
  src/main/java/diet/dietmanager/DietManager.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionEdit.java
  src/main/java/logic/commands/profile/ProfileView.java
  src/main/java/storage/diet/DietStorage.java
  src/main/java/ui/diet/dietmanager/DietManagerUi.java
  src/test/java/diet/dietmanager/DietManagerTest.java
  src/test/java/diet/dietmanager/DietSessionStorageTest.java
  src/test/java/diet/dietmanager/saves/2020-04-04 breakfast.json
  src/test/java/diet/dietmanager/saves/2020-04-04 lunch.json
  src/test/java/diet/dietmanager/saves/2020-05-05 breakfast.json
Labels: diet

#218 Write more junit test for commands in dietmanager
  src/main/java/diet/dietmanager/DietManager.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionClear.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionCreate.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionEdit.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionList.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionSearch.java
  src/main/java/ui/diet/dietmanager/DietManagerUi.java
  src/test/java/diet/dietmanager/DietManagerTest.java
  src/test/java/logic/commands/diet/dietmanager/DietSessionClearTest.java
  src/test/java/logic/commands/diet/dietmanager/DietSessionCreateTest.java
  src/test/java/logic/commands/diet/dietmanager/DietSessionDeleteTest.java
  src/test/java/logic/commands/diet/dietmanager/DietSessionEditTest.java
  src/test/java/logic/commands/diet/dietmanager/DietSessionSearchTest.java
Labels: diet

#219 update user stories in DG
  docs/DeveloperGuide.md
Labels: documentation

#220 Add javaDoc for all public Workout Session methods
  src/main/java/logic/commands/workout/workoutsession/WorkoutSessionAdd.java
  src/main/java/logic/commands/workout/workoutsession/WorkoutSessionDelete.java
  src/main/java/logic/commands/workout/workoutsession/WorkoutSessionEnd.java
  src/main/java/logic/commands/workout/workoutsession/WorkoutSessionHelp.java
  src/main/java/logic/commands/workout/workoutsession/WorkoutSessionList.java
  src/main/java/logic/commands/workout/workoutsession/WorkoutSessionSearch.java
  src/main/java/logic/commands/workout/workoutsession/WorkoutSessionWrong.java
  src/main/java/logic/parser/WorkoutSessionParser.java
  src/main/java/models/Exercise.java
  src/main/java/models/ExerciseList.java
  src/main/java/storage/workout/WorkoutSessionStorage.java
  src/main/java/ui/workout/workoutsession/WorkoutSessionUi.java
  src/main/java/workout/workoutsession/WorkoutSession.java
  src/test/java/logic/parser/WorkoutSessionParserTest.java
Labels: workout

#221 Update User guide
  docs/UserGuide.md
Labels: diet, documentation, profile, workout

#222 Update search format for diet session in help message and user guide
  docs/UserGuide.md
  src/main/java/ui/diet/dietsession/DietSessionUi.java
Labels: diet, documentation

#224 change name of PPP files
  docs/AboutUs.md
  docs/team/cfzeon.md
  docs/team/wgzesg.md
  docs/team/yujinyang1998.md
  docs/team/zeon.md
  docs/team/zsk612.md
Labels: documentation

#225 Update personal ppp
  docs/AboutUs.md
  docs/team/cfzeon.md
  src/main/java/storage/diet/DietStorage.java
Labels: documentation

#227 Update ppp
  docs/team/zsk612.md
Labels: diet, documentation

#226 Edit format
  docs/team/yujinyang1998.md
  src/main/java/models/PastRecordList.java
  src/main/java/seedu/duke/Duke.java
Labels: documentation, workout

#229 Add PPP
  build.gradle
  docs/AboutUs.md
  docs/team/tienkhoa16.md
  docs/team/wgzesg.md
  docs/team/zsk612.md
  src/main/java/diet/dietmanager/DietManager.java
  src/main/java/diet/dietsession/DietSession.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionClear.java
  src/main/java/logic/commands/profile/ProfileView.java
  src/main/java/logic/commands/workout/workoutmanager/ClearWS.java
  src/main/java/logic/parser/CommonParser.java
  src/main/java/logic/parser/DietManagerParser.java
  src/main/java/logic/parser/DietSessionParser.java
  src/main/java/models/Profile.java
  src/main/java/profile/Constants.java
  src/main/java/ui/CommonUi.java
  src/main/java/ui/profile/ProfileUi.java
  src/test/java/logic/commands/profile/ProfileViewTest.java
  src/test/java/logic/parser/DietManagerParserTest.java
  src/test/java/profile/ProfileSessionTest.java
Labels: documentation

#230 Update jar file name in UG
  docs/UserGuide.md
Labels: documentation

#231 Update dg links and ppp
  docs/DeveloperGuide.md
  docs/team/yujinyang1998.md
Labels: documentation

#232 Update UG examples in Main and Profile
  docs/UserGuide.md
  docs/pictures/UG_screenshots/add-profile-step-1.png
  docs/pictures/UG_screenshots/add-profile-step-2.png
  docs/pictures/UG_screenshots/add-profile-step-3.png
  docs/pictures/screenshots-labelling-template.pptx
Labels: documentation

#233 Add exception handling for corrupted json file and junit test
  docs/UserGuide.md
  docs/pictures/UG_screenshots/new-dietsession-step-1.png
  docs/pictures/UG_screenshots/new-dietsession-step-2.png
  docs/pictures/UG_screenshots/new-dietsession-step-3.png
  docs/pictures/UG_screenshots/new-dietsession-step-4.png
  src/main/java/diet/dietmanager/DietManager.java
  src/main/java/storage/diet/DietStorage.java
  src/main/java/ui/diet/dietmanager/DietManagerUi.java
  src/test/java/diet/dietmanager/DietManagerTest.java
  src/test/java/diet/dietmanager/DietSessionStorageTest.java
  src/test/java/diet/dietmanager/corruptedsaves/2020-11-09 unspecified.json
  src/test/java/saves/ProfileCommandsTest/profileDataFile.json
Labels: bug, diet

#234 Update UG, add missing javadoc
  README.md
  docs/UserGuide.md
  src/main/java/logic/commands/Command.java
  src/main/java/logic/commands/CommandResult.java
  src/main/java/logic/parser/DateParser.java
  src/main/java/seedu/duke/Constant.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/storage/profile/ProfileStorage.java
  src/main/java/ui/CommonUi.java
Labels: documentation

#235 change new diet session step 4 image
  docs/pictures/UG_screenshots/new-dietsession-step-4.png
Labels: bug, documentation

#237 Update user stories in DG
  docs/DeveloperGuide.md
  docs/team/tienkhoa16.md
Labels: documentation

#240 Add more javadoc for project
  src/main/java/diet/dietmanager/DietManager.java
  src/main/java/diet/dietsession/DietSession.java
  src/main/java/exceptions/diet/NegativeCaloriesException.java
  src/main/java/exceptions/diet/NoNameException.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionClear.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionCreate.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionDelete.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionEdit.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionHelp.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionList.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionSearch.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionWrong.java
  src/main/java/logic/commands/diet/dietsession/FoodItemAdd.java
  src/main/java/logic/commands/diet/dietsession/FoodItemClear.java
  src/main/java/logic/commands/diet/dietsession/FoodItemDelete.java
  src/main/java/logic/commands/diet/dietsession/FoodItemHelp.java
  src/main/java/logic/commands/diet/dietsession/FoodItemList.java
  src/main/java/logic/commands/diet/dietsession/FoodItemSearch.java
  src/main/java/logic/commands/diet/dietsession/FoodItemWrong.java
  src/main/java/logic/commands/workout/workoutmanager/ByeWS.java
  src/main/java/logic/commands/workout/workoutmanager/ClearWS.java
  src/main/java/logic/commands/workout/workoutmanager/DeleteWS.java
  src/main/java/logic/commands/workout/workoutmanager/EditWS.java
  src/main/java/logic/commands/workout/workoutmanager/HelpWS.java
  src/main/java/logic/commands/workout/workoutmanager/ListWS.java
  src/main/java/logic/commands/workout/workoutmanager/NewWS.java
  src/main/java/logic/commands/workout/workoutmanager/SearchWS.java
  src/main/java/logic/commands/workout/workoutmanager/WrongWS.java
  src/main/java/logic/parser/DateParser.java
  src/main/java/logic/parser/DietManagerParser.java
  src/main/java/logic/parser/DietSessionParser.java
  src/main/java/logic/parser/WorkoutManagerParser.java
  src/main/java/models/PastRecordList.java
  src/main/java/models/PastWorkoutSessionRecord.java
  src/main/java/seedu/duke/Constant.java
  src/main/java/storage/diet/DietStorage.java
  src/main/java/storage/workout/WorkOutManagerStorage.java
  src/main/java/ui/CommonUi.java
  src/main/java/ui/diet/dietmanager/DietManagerUi.java
  src/main/java/ui/diet/dietsession/DietSessionUi.java
  src/main/java/ui/workout/workoutmanager/WorkoutManagerUi.java
  src/main/java/workout/workoutmanager/WorkoutManager.java
Labels: documentation

#242 Update DG for workout session help
  docs/DeveloperGuide.md
  docs/pictures/jinyang/ParseInputWorkoutSession.png
  docs/pictures/jinyang/ReturnMsgToUser.png
  docs/pictures/jinyang/WokroutSessionHelp.png
  docs/pictures/jinyang/WokroutSessionHelp.puml
  docs/pictures/jinyang/WorkoutSessionAdd.png
  docs/pictures/jinyang/WorkoutSessionAdd.puml
  docs/pictures/jinyang/WorkoutSessionDelete.png
  docs/pictures/jinyang/WorkoutSessionDelete.puml
  docs/pictures/jinyang/WorkoutSessionEnd.png
  docs/pictures/jinyang/WorkoutSessionEnd.puml
  docs/pictures/jinyang/WorkoutSessionList.png
  docs/pictures/jinyang/WorkoutSessionList.puml
  docs/pictures/jinyang/WorkoutSessionSearch.png
  docs/pictures/jinyang/WorkoutSessionSearch.puml
  docs/team/yujinyang1998.md
Labels: documentation

#244 update uml diagram for dg
  docs/DeveloperGuide.md
  docs/pictures/Zeon/CreateDietSession.png
  docs/pictures/Zeon/CreateDietSession.puml
  docs/pictures/Zeon/DietSessionClear.png
  docs/pictures/Zeon/DietSessionClear.puml
  docs/pictures/Zeon/DietSessionDelete.png
  docs/pictures/Zeon/DietSessionDelete.puml
  docs/pictures/Zeon/DietSessionEdit.png
  docs/pictures/Zeon/DietSessionEdit.puml
  docs/pictures/Zeon/DietSessionList.png
  docs/pictures/Zeon/DietSessionList.puml
  docs/pictures/Zeon/SearchDietSession.png
  docs/pictures/Zeon/SearchDietSession.puml
  src/main/java/diet/dietmanager/DietManager.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionClear.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionList.java
  src/main/java/logic/commands/diet/dietmanager/DietSessionSearch.java
  src/main/java/ui/diet/dietmanager/DietManagerUi.java
Labels: documentation

#246 Update ug for workout session add and dg typo
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/pictures/jinyang/AddCommand.png
  docs/pictures/jinyang/AddCommandMessage.png
  docs/pictures/jinyang/AddCommandStart.png
Labels: documentation

#247 update dg
  docs/DeveloperGuide.md
  src/main/java/ui/diet/dietmanager/DietManagerUi.java
Labels: documentation

#248 Update DG diagrams
  docs/DeveloperGuide.md
  docs/pictures/khoa/AddProfile.png
  docs/pictures/khoa/AddProfile.puml
  docs/pictures/khoa/DeleteProfile.png
  docs/pictures/khoa/DeleteProfile.puml
  docs/pictures/khoa/EditProfile.png
  docs/pictures/khoa/EditProfile.puml
  docs/pictures/khoa/ParseInput.png
  docs/pictures/khoa/ParseInput.puml
  docs/pictures/khoa/ShowMessage.png
  docs/pictures/khoa/ShowMessage.puml
  docs/pictures/khoa/ViewProfile.png
  docs/pictures/khoa/ViewProfile.puml
  docs/team/tienkhoa16.md
  docs/team/wgzesg.md
  docs/team/yujinyang1998.md
Labels: documentation

#250 Update DG for wrokout session
  build.gradle
  docs/DeveloperGuide.md
  docs/pictures/jinyang/ParseInputWorkoutSession.png
  docs/pictures/jinyang/ParseInputWorkoutSession.puml
  docs/pictures/jinyang/ReturnMsgToUser.png
  docs/pictures/jinyang/ReturnMsgToUser.puml
  docs/pictures/jinyang/WorkoutSessionAdd.png
  docs/pictures/jinyang/WorkoutSessionAdd.puml
  docs/pictures/jinyang/WorkoutSessionDelete.png
  docs/pictures/jinyang/WorkoutSessionDelete.puml
  docs/pictures/jinyang/WorkoutSessionEnd.png
  docs/pictures/jinyang/WorkoutSessionEnd.puml
  docs/pictures/jinyang/WorkoutSessionList.png
  docs/pictures/jinyang/WorkoutSessionList.puml
  docs/team/yujinyang1998.md
Labels: documentation

#256 Update dg
  docs/DeveloperGuide.md
  docs/pictures/jinyang/ParseInputWorkoutSession.png
  docs/pictures/jinyang/ReturnMsgToUser.jpg
  docs/pictures/jinyang/ReturnMsgToUser.png
  docs/pictures/jinyang/ReturnMsgToUser.puml
  docs/pictures/jinyang/WokroutSessionHelp.png
  docs/pictures/jinyang/WokroutSessionHelp.puml
  docs/pictures/jinyang/WorkoutSessionAdd.png
  docs/pictures/jinyang/WorkoutSessionAdd.puml
  docs/pictures/jinyang/WorkoutSessionDelete.png
  docs/pictures/jinyang/WorkoutSessionDelete.puml
  docs/pictures/jinyang/WorkoutSessionEnd.png
  docs/pictures/jinyang/WorkoutSessionEnd.puml
  docs/pictures/jinyang/WorkoutSessionList.png
  docs/pictures/jinyang/WorkoutSessionList.puml
  docs/pictures/jinyang/WorkoutSessionSearch.png
  docs/pictures/jinyang/WorkoutSessionSearch.puml
Labels: documentation

#261 Update ug dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#262 Update coverage report link DG
  docs/DeveloperGuide.md
Labels: documentation

#266 Update ppp
  docs/team/yujinyang1998.md
Labels: documentation

#270 Update ppp
  docs/team/wgzesg.md
  docs/team/yujinyang1998.md
Labels: documentation

#274 Update ug
  docs/UserGuide.md
Labels: documentation
